version: '3'
services:
  nginx:
    image: nginx:1.17
    ports:
      - "80:80"
    volumes:
      - "./docker-configs/nginx.conf:/etc/nginx/conf.d/default.conf"
      - ".:/app:cached"

  php:
    build:
      context: ./docker-configs/php
    volumes:
      - "./docker-configs/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ".:/app:cached"
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ad_db
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
volumes:
  postgresdata: